### ISSUE TITLE
Publish on grafana.com

### ISSUE THREAD

**Issue by alexanderzobnin** [petrslavotinek/grafana-carpetplot#1]
Hi, @petrslavotinek Great job! Did you think about publishing your panel on grafana.com? If you need help, let me know.

**Comment by petrslavotinek** [comment]
Hi, Thanks. I posted it on grafana community forum (https://community.grafana.com/t/new-panel-plugin-carpet-plot/1334/) but they haven't published it yet.
I'll try to send a pull request to the plugin repository.

**Comment by alexanderzobnin** [comment]
Cool.

**Comment by petrslavotinek** [comment]
Published: https://grafana.com/plugins/petrslavotinek-carpetplot-panel.
I'm open to any ideas on how to improve this plugin.
