### ISSUE TITLE
error after upgrade to 0.1.0

### ISSUE THREAD

**Issue by diegoarioza** [petrslavotinek/grafana-carpetplot#13]
![erro_carpet](https://user-images.githubusercontent.com/11810798/33776180-b6bada4e-dc27-11e7-9867-c27b70349b75.png)

**Comment by petrslavotinek** [comment]
What version of grafana are you using?
Could you also post here screenshots of Display and Axes settings?

**Comment by jameyg42** [comment]
same issue here
Grafana v4.6.2 (commit: 8db5f08)
Chrome 62 / Win10

there's nothing to screenshot though (the error prevents me from adding a new carpet-plot panel).  

for some reason, interpolateRgbBasis is undefined in ramp.js.  I'm not sure how to interpret Babel output and Chrome's messing up source maps making it hard to debug, but in the compiled ramp.js, it seems like 
```
            setters: [function(_d) {
                interpolateRgbBasis = _d.interpolateRgbBasis;
            }
 ```
needs to be called before _export, but that doesn't appear to be happening leaving interpolateRgbBasis undefined.  Could this possible be related to d3 4.5 and d3-scale-chromatic 1.1.1 is already packaged by Grafana?
