### ISSUE TITLE
"interpolateRgbBasis is not a function" error on fresh installation

### ISSUE THREAD

**Issue by pasilan** [petrslavotinek/grafana-carpetplot#15]
Hi,
After successfully installing CarpetPlot I'm getting this error message in Grafana:
"Plugin component error Error: interpolateRgbBasis is not a function
  Evaluating http://hostname/public/plugins/petrslavotinek-carpetplot-panel/libs/d3-scale-chromatic/diverging/BrBG.js
  Evaluating http://hostname/public/plugins/petrslavotinek-carpetplot-panel/libs/d3-scale-chromatic/index.js
  Evaluating http://hostname/public/plugins/petrslavotinek-carpetplot-panel/canvas/rendering.js
  Evaluating http://hostname/public/plugins/petrslavotinek-carpetplot-panel/carpetplot-ctrl.js
  Evaluating http://hostname/public/plugins/petrslavotinek-carpetplot-panel/module.js
  Loading plugins/petrslavotinek-carpetplot-panel/module
    at eval (ramp.js:4)
    at Object.execute (BrBG.js:16)
    at O (index.js:33)
    at E (index.js:33)
    at E (index.js:33)
    at E (index.js:33)
    at E (index.js:33)
    at E (index.js:33)
    at A (index.js:33)
    at index.js:33
"
InterpolateRgbBasis seems to refer to some D3 function.
All JavaScript files are loaded successfully from server (http code 200) so there aren't any JS-files missing.

Any tips how to fix this?

Using Grafana v4.6.3 and Chrome "63.0.3239.84".

**Comment by petrslavotinek** [comment]
It's been fixed in latest version but pull request in plugin repository hasn't been merged yet.
In the meantime, could you try downloading it directly from here and replacing dist folder?

**Comment by pasilan** [comment]
Replacing **dist** directly from here fixed the problem for IE11 but not for Chrome.

**Comment by petrslavotinek** [comment]
Is it still the same error? Have you tried to clear the browser's cache?

On Jan 2, 2018 18:55, Pasi Lantiainen <notifications@github.com> wrote:

Replacing dist directly from here fixed the problem for IE11 but not for Chrome.

**Comment by pasilan** [comment]
Sorry, my bad. Chrome works too! Excellent! 👍
