### ISSUE TITLE
Incompatibility with Grafana v5

### ISSUE THREAD

**Issue by soundstorm** [petrslavotinek/grafana-carpetplot#17]
Hello,
I just upgraded to v5, now the panels won't work anymore:

`t is not a function. (In 't(a?Math.max(0,Math.min(1,r)):r)', 't' is undefined)`

```
e@https://grafana.arduino-hannover.de/public/build/vendor.2c3c591224fb193f7fd3.js:127:171106
https://grafana.arduino-hannover.de/public/build/vendor.2c3c591224fb193f7fd3.js:127:67314
a@https://grafana.arduino-hannover.de/public/build/vendor.2c3c591224fb193f7fd3.js:127:66943
addPoints
addCarpetplot
render
```

**Comment by petrslavotinek** [comment]
Hello,
I'm using grafana v5.0.2 and plugin version 0.1.1 and it works.
Which version of plugin do you use?
Could you try to create new dashboard with this panel?

The posted error is pointing to Autolinker.js. I think that the plugin shouldn't be using it internally.

**Comment by soundstorm** [comment]
Somehow I was using an older version, but just updated, now it gives me
`colorScales[panel.color.mode] is not a function. (In 'colorScales[panel.color.mode](min, max)', 'colorScales[panel.color.mode]' is undefined)` and still a not well looking backend:
![bildschirmfoto 2018-03-19 um 14 30 51](https://user-images.githubusercontent.com/193273/37598342-3ef35acc-2b82-11e8-99d9-6d4eb6dc70bd.png)

**Comment by soundstorm** [comment]
Okay, PageSpeed cached older versions so that messed up everything!
