### ISSUE TITLE
Graph doesn't respect the "Override relative time" setting

### ISSUE THREAD

**Issue by pimeys** [petrslavotinek/grafana-carpetplot#5]
The graph would be more useful if it could be able to show a bigger time range than the rest of my dashboard. Now in Grafana there's a setting for a graph called `Override relative time` which should force this specific panel to a certain range. Unfortunately for this plugin it does nothing.

**Comment by pimeys** [comment]
:+1:

**Comment by petrslavotinek** [comment]
Hi, the updated version has just been merged to plugin repository and should be available for download.
